<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * FamilyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FamilyRepository extends EntityRepository
{
    public function getFamilyLike($name,$max_result)
    {
        $name = "%" . $name . "%";

        $qb = $this->createQueryBuilder('f')
            ->select('f.name')
            ->where('f.name LIKE :name')
            ->setParameter('name', $name)
            ->setMaxResults($max_result)
            ->getQuery();

        return $qb->getResult();

    }
}
