<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * GenusRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GenusRepository extends EntityRepository
{
    public function getGenusLike($name,$max_result)
    {
        $name =  "%" . $name . "%";
        $qb = $this->createQueryBuilder('g')
            ->select('g.name')
            ->where('g.name LIKE :name')
            ->setParameter('name', $name)
            ->setMaxResults($max_result)
            ->getQuery();

        return $qb->getResult();

    }

}
