<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * SpecieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SpecieRepository extends EntityRepository
{
    public function getSpecieLike($name,$max_result)
    {

        $qb = $this->createQueryBuilder('sp')
            ->select('sp.name')
            ->where('sp.name LIKE :name')
            ->setParameter('name', $name)
            ->setMaxResults($max_result)
            ->getQuery();

        return $qb->getResult();

    }

    public function getGenusSpecieLike($name,$max_result)
    {
        $name =  "%" . $name . "%";
        $qb = $this->createQueryBuilder('s')
            ->select('s.name as species, g.name as genus, s.id')
            ->join('s.genus','g')
            ->where('g.name LIKE :name')
            ->orWhere('s.name LIKE :name')
            ->orderBy('g.name','ASC')
            ->orderBy('s.name','ASC')
            ->setParameter('name', $name)
            ->setMaxResults($max_result)
            ->getQuery();

        return $qb->getResult();

    }
}
