<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * SubFamilyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SubFamilyRepository extends EntityRepository
{
    public function getSubFamilyLike($name,$max_result)
    {
        $name =  "%" . $name . "%";
        $qb = $this->createQueryBuilder('sf')
            ->select('sf.name')
            ->where('sf.name LIKE :name')
            ->setParameter('name', $name)
            ->setMaxResults($max_result)
            ->getQuery();

        return $qb->getResult();

    }
}
